name: shopping
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_launcher_icons: ^0.13.1
  get: 4.6.6
  google_fonts: ^6.2.0
  motion_toast: ^2.8.0
  persistent_bottom_nav_bar: ^5.0.2
  pretty_dio_logger: ^1.3.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
